#!/bin/bash

jupyter labextension install --no-build @pyviz/jupyterlab_pyviz
jupyter labextension install --no-build jupyterlab-nvdashboard  # client-side component; server-side installed via conda/pip
jupyter serverextension enable jupyterlab_sql --py --sys-prefix
jupyter lab build
